### ISSUE TITLE
Allow submit MapReduce jobs through an ssh connection

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1156]
Solution proposed in #1113 to submit MapReduce jobs fromt he AzureBatch container. This can be useful in other scenarios where the worker node does not have full access to hadoop

**Comment by j-coll** [comment]
New configuration params:

```yml
- id: "hadoop"
  variant:
    manager: "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine"
    options:
      ...
      # Define the way of executing MapReduce jobs.
      opencga.mr.executor: "ssh"  # Use external hadoop installation. ssh to a host edge node
      opencga.mr.executor.ssh.host: ""             # Hadoop edge node host name
      opencga.mr.executor.ssh.user: ""             # Hadoop edge node user name
      opencga.mr.executor.ssh.key: "~/.ssh/id_rsa" # Hadoop edge node ssh-key file
    # opencga.mr.executor.ssh.password: ""         # Hadoop edge node password. Only if ssh-key is not present. Requires sshpass to run
```
