### ISSUE TITLE
Storage engine configuration incorrect for SSH Mapreduce

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1219]
The current initialisation script doesn't appear to set the correct properties for the storage engine to use the SSH executor. 

```
ariant:
    manager: org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine
    options:
      database.name: opencga
      dbadaptor.phoenix.fetch_size: -1
      annotator: cellbase_rest
      annotator.cellbase.exclude: expression
      annotator.cellbase.use_cache: true
      annotator.cellbase.imprecise_variants: true
      species: null
      assembly: null
      opencga.storage.hadoop.jar-with-dependencies: opencga-storage-hadoop-core-1.4.1-dev-jar-with-dependencies.jar
      opencga.archive.chunk_size: 1000
      hadoop.load.archive.batch.size: 3
      hadoop.load.variant.batch.size: 500
      opencga.archive.table.presplit.size: 500
      opencga.archive.table.compression: gz
      opencga.variant.table.presplit.size: 500
      opencga.variant.table.compression: snappy
      opencga.sample-index.table.presplit.size: 15
      opencga.sample-index.table.compression: snappy
      opencga.storage.hadoop.variant.hbase.namespace: ''
      stats.default-genotype: 0/0
      stats.multiallelic: false
      intersect.active: true
      intersect.always: false
      intersect.params.threshold: 3
      limit.default: 1000
      limit.max: 5000
      sample.limit.default: 100
      sample.limit.max: 1000
      opencga.hadoop.bin: hadoop
      opencga.mr.executor: system
      mapreduce.map.cpu.vcores: 1
      mapreduce.map.memory.mb: 2560
      opencga.variant.table.mapreduce.map.java.opts: -Xmx2048m,-XX:+UseG1GC,-Djava.util.concurrent.ForkJoinPool.common.parallelism=1
      opencga.storage.hadoop.hbase.merge.archive.scan.batchsize: 2000
      opencga.storage.hadoop.mapreduce.scanner.timeout: 300000

```

Missing:

```
      # Use external hadoop installation. ssh to a host edge node
      # opencga.mr.executor: "ssh"                 # Uncomment to enable
      opencga.mr.executor.ssh.host: ""             # Hadoop edge node host name
      opencga.mr.executor.ssh.user: ""             # Hadoop edge node user name
      # opencga.mr.executor.ssh.key: "~/.ssh/id_rsa" # Hadoop edge node ssh-key file
      opencga.mr.executor.ssh.password: ""         # Hadoop edge node password. Only if ssh-key is not present. Requires sshpass to run
      opencga.mr.executor.ssh.remote_opencga_home: "" # Remote opencga home location. Only if different than local location.
```
