### ISSUE TITLE
Use wrong log4j config file in opencga.war

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1221]
Logs from opencga.war are not being prompted as expected. Apparently, they are taking a different log4j.properties file.

Actual *v1.4.1-dev":
```
INFO [2019-03-25 10:48:25,601]  [OpenCGAWSServer.java:191] [http-bio-8080-exec-1]  | Starting OpenCGA REST server, initializing OpenCGAWSServer
```

Expected "v1.4.0-rc3-dev":
```
2016-06-30 17:22:36 [http-nio-8080-exec-3] INFO  OpenCGAWSServer:183 - | Starting OpenCGA REST server, initializing OpenCGAWSServer
```

Starting tomcat with log4j debug enabled with `export JAVA_OPTS="-Dlog4j.debug"` shows:

```
log4j: Trying to find [log4j.xml] using context classloader WebappClassLoader
  context: /opencga_tomcat
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@439f5b3d
.
log4j: Trying to find [log4j.xml] using WebappClassLoader
  context: /opencga_tomcat
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@439f5b3d
 class loader.
log4j: Trying to find [log4j.xml] using ClassLoader.getSystemResource().
log4j: Trying to find [log4j.properties] using context classloader WebappClassLoader
  context: /opencga_tomcat
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@439f5b3d
.
log4j: Using URL [jar:file:/opt/apache-tomcat-7.0.62/webapps/opencga_tomcat/WEB-INF/lib/BigWig-1.0.jar!/log4j.properties] for automatic log4j configuration.
log4j: Reading configuration from URL jar:file:/opt/apache-tomcat-7.0.62/webapps/opencga_tomcat/WEB-INF/lib/BigWig-1.0.jar!/log4j.properties
log4j: Parsing for [root] with value=[INFO, stdout].
log4j: Level token is [INFO].
log4j: Category root set to INFO
log4j: Parsing appender named "stdout".
log4j: Parsing layout options for "stdout".
log4j: Setting property [conversionPattern] to [%p [%d{ISO8601}]  [%F:%L] [%t]  %m%n].
log4j: End of parsing for "stdout".
log4j: Parsed "stdout" options.
log4j: Parsing for [org.broad.tribble] with value=[ERROR, stdout].
log4j: Level token is [ERROR].
log4j: Category org.broad.tribble set to ERROR
log4j: Parsing appender named "stdout".
log4j: Appender "stdout" was already parsed.
log4j: Handling log4j.additivity.org.broad.tribble=[null]
log4j: Parsing for [org.broad.igv] with value=[ERROR, stdout].
log4j: Level token is [ERROR].
log4j: Category org.broad.igv set to ERROR
log4j: Parsing appender named "stdout".
log4j: Appender "stdout" was already parsed.
log4j: Handling log4j.additivity.org.broad.igv=[null]
log4j: Finished configuring.
```
