### ISSUE TITLE
New Analysis configuration section

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#1396]
We need to add some extra configuration for the new Analysis Framework developed. This will be added into _configuration.yml_ file. An initial proposal:

```
analysis:
  tempJobsDir: "${OPENCGA.ANALYSIS.JOBS.DIR}"      # Deprecated
  analysisDir: "${OPENCGA.ANALYSIS.ANALYSIS.DIR}"  # folder with the analysis
  scratchDir: "${OPENCGA.ANALYSIS.SCRATCH.DIR}"
  execution:   # Different from Catalog Execution!
    id: ${OPENCGA.ANALYSIS.EXECUTION.MODE}   # Accepted values are Slurm, LSF, Azure Batch, LocalThread
    defaultQueue: "fast"
    availableQueues:
      - fast: "alignmentIndex"
      - slow: "coverage,alignmentStats"
    options:
      local.maxConcurrentJobs: 2
  mapreduce:
    maxConcurrentJobs: 2
  spark:
    host: "${OPENCGA.ANALYSIS.SPARK.HOST}"
    port: "${OPENCGA.ANALYSIS.SPARK.PORT}"
    options:     # Spark properties from https://spark.apache.org/docs/latest/configuration.html#viewing-spark-properties
      spark.executor.memory: "1g"
```

Note:
- There are two _execution_ sections now, the current one should be moved to _catalog_ and a new one is created in _analysis_. The reason for this is that contain some different fields and the queues can be different
- _maxConcurrentIndexJobs_ moved to storage?
- All MAven properties must start with OPENCGA.ANALYSIS
