### ISSUE TITLE
Clean and improve storage-configuration.yml

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1412]
```yml

server: # Same structure as in genreal configuration
  ...
alignment:
  ...

clinical:
  ...

search:
  # same

variant:
  defaultEngine: "mongodb"
  options: # general variant options
    transform.threads: 4
    load.threads: 4
    ...
  engines:
    - id : "mongodb"
      class : "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine"
      database:
        hosts: []
        user: ""
        password: ""
        options: { ... }
      options: # Mongodb specific options 
        mongodb.collection.variants: "variants"
        mongodb.collection.stage: "stage"
        ...
    - id : "hadoop"
      class : "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine"
      options: # Hadoop specific options 
          hadoop.archive.table.presplit.size: 500
          hadoop.archive.table.compression: "gz"
          ...

```
