### ISSUE TITLE
Configuration changes

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#1415]
We need to do a few changes to the main OpenCGA configuration file.

- Add:
  - A new **batch** section in **catalog** for the execution of internal tasks.
```yml
     batch:
         id: ""        # SGE, SLURM
         queue: ""     # Queue id
         timeout: 60 # Maximum time in minutes a task can be running
```

- Remove:
  - **userDefaultQuota**
  - **tempJobsDir**
  - **toolDir**
  - **catalog.offset**: Not in use since 1.4.0

- Rename:
  - **dataDir** for **workspace**
  - **catalog.search** for **catalog.searchEngine**

- Other changes:
  - **catalog.searchEngine** should have the same database sections as **catalog.database**
  - **audit** section for something similar to:
```yml
     audit:
       manager: ""             # Java manager of the audit implementation to be used to audit. If empty, catalog database will be used.
       maxDocuments: 20000000  # Maximum number of documents that will be created in the audit collection.
       maxSize: 100            # Maximum size that the audit collection will have in Gigabytes (GB).
```
