### ISSUE TITLE
Add FilterCount and MeanQuality to VariantStats

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1502]
VariantStats provide, for each variant, a set of counters and frequencies given the genotype values of a set of samples. This stats do not include any value referring to the FILTER or QUALITY of the variants. These values can be found in the FileAttributes of the study.

## Fields to add
- `filterCount : Map<String, Integer>`
Will contain one key for each seen Filter value on this variant. The value will be incremented in one for each sample within the cohort that has a non-missing genotype.
The FILTER field may contain multiple values separated by `;`, so the sum of all values may be larger than the number of samples in the cohort.
- `filterFrequency : Map<String, Float>`
This map will be produced by dividing each value from the `filterCount` map by the number of non-missing genotypes.
- `meanQuality : Float`
The weighted average of the Quality, computed only for non-missing samples.

## Example
Given this variant, with two files, each of them with 3 samples
```yml
variant:
  id: "1:100:A:C"
  studies:
    - studyId: "study"
      files:
        - fileId: "file01"
          attributes:
            FILTER: "PASS"
            QUAL: 40
        - fileId: "file02"
          attributes:
            FILTER: "filter1;filter2"
            QUAL: 20
      samples:
        - ["0/0", "file01_sample01"] # file01
        - ["0/1", "file01_sample02"] #  "
        - ["1/1", "file01_sample03"] #  "
        - ["0/0", "file02_sample01"] # file02
        - ["1/1", "file02_sample02"] #  "
        - ["./.", "file02_sample03"] #  "
```

The statistics for this variant, for a cohort containing all samples:
```yaml
filterCount:
  PASS: 3
  filter1: 2
  filter2: 2
filterFreq:
  PASS:    0.6 # 3/5
  filter1: 0.4 # 2/5
  filter2: 0.4 # 2/5
meanQuality: 32 # (40*3+20*2)/5
```
