### ISSUE TITLE
Does opencga-1.4.1 non docker supports azure batch service

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1656]
Hi Team,

We have opencga-1.4.1 currently running in production, to speed up of transforming and data loading process we would like to use azure batch service.

So the question is does opencga-1.4.1 non-docker instance supports azure batch service? 

if yes could you please share the configuration required to use azure batch service.

Also, we looked into POC for azure batch and it clearly asks for the docker image name as below, is this mandatory?

execution:
  mode: AZURE
    ...
  options:
    #Azure Batch Service information
    batchAccount : "batchAccount"
    batchKey : "batchKey"
    batchUri : "https://batchservice.uksouth.batch.azure.com"
    batchPoolId : "poolId"
    **dockerImageName : "openCGADockerImageName" # preconfigured docker image
    dockerArgs : "dockerRunOptions"   # e,g; mount points etc.**

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

Azure Batch was introduced at v1.4.2.
This executor always uses a docker to run the jobs. Typically, the used image would be "", and the dockerArgs would be the required to mount some folder, but this will depend on your AzureBatch installation.

```yaml
execution:
  mode: AZURE
  options:
     dockerImageName: "opencb/opencga-batch:f0b252daf"
     dockerArgs: "--rm -v  /mnt/opencga/conf:/opt/opencga/conf -v /mnt/opencga/sessions:/opt/opencga/sessions -v /mnt/opencga/variants:/opt/opencga/variants"
```
