### ISSUE TITLE
How to use SGE with OpenCGA

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1659]
Hi Team,

We have SGE scheduler and need your help to configure with OpenCGA, could you please share if you have any documents or step to configure SGE.

Thanks for your all support.

**Comment by Mohammedhusen** [comment]
Hi Team,

Could you please update on this?

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

To use SGE you should first configure the "analysis.execution" section in the configuration.yml file with the default queue that you want to use

```
analysis:
  execution:
    # Accepted values are "local", "SGE", "azure-batch", "k8s"
    # see org.opencb.opencga.master.monitor.executors.ExecutorFactory
    id: "SGE"
    defaultQueue: "???"            # Default queue to be used to submit jobs
```

The OpenCGA Master (opencga-admin.sh catalog daemon --start ) should be running in a node with access to the SGE commands, i.e. "qsub", "qacct" and "qstat"

Also, I should warn that this executor is not being actively maintained, so it might throw some errors. If that's the case, please let me know and I'll try to fix them.

**Comment by j-coll** [comment]
In case that you are using OpenCGA v1.4.x, the configuration.yml section to modify is this one:

```yaml
execution:
  mode: "SGE"
  defaultQueue: "???"
```
