### ISSUE TITLE
CatalogAuthenticationException when logging in with imported LDAP user

### ISSUE THREAD

**Issue by mwhamgenomics** [opencb/opencga#1681]
When I try to log in with an imported LDAP user, `LDAPAuthenticationManager.getDN` is hard-coded to get the username from either the LDAP field `dn` or `distinguishedname`. My organisation's LDAP server doesn't use either of those fields to store the username, so OpenCGA finds nothing and passes an empty string `""` as the username/security principal. We should make the security principal field configurable for users with different LDAP setups.

**Comment by pfurio** [comment]
Hi @mwhamgenomics, can you check after this commit? I've added the following new keys to be configured:
```yaml
dnKey: dn        # Key to get the user's DN or RDN unique identifier. By default, 'dn'.
uidKey: uid      # Key to get the user id to be used in OpenCGA. By default, 'uid'.
uidFormat: "%s"  # Formatter to extract the user id if the uid is contained within a larger string. By default, '%s' to take the whole string.
```
