### ISSUE TITLE
Max number of threads - maxWaitQueueSize - should be configurable.

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#468]
Max number of connections to mongodb - maxWaitQueueSize - is fixed to 100 threads in mongodb java driver in opencga, which is not enough. This should be configurable as it is a limiting factor.

**Comment by j-coll** [comment]
Actually, it is. 

MaxWaitQueueSize is defined as `threadsAllowedToBlockForConnectionMultiplier * connectionsPerHost`
The default connectionMultiplier is 5, and the connectionsPerHost is 20. You can modify the number of "connectionsPerHost" in the storage-configuration.yml file, in the options of the database configuration.

Let's see in an example. See the last section with the default value of connectionsPerHost:

```yml
storageEngines:
- id: "mongodb"
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager"
    options:
      transform.threads: 4
      transform.format: "avro"
      load.batch.size: 100
      load.threads: 6
      .....
    database:
      hosts:
      - "localhost:27017"
      user: ""
      password: ""
      options:    ## This is intended for database specific options such as --authenticationDatabase in MongoDB
        authenticationDatabase: 
        readPreference: "secondaryPreferred"
        connectionsPerHost : 20
``` 
- [ ] This configuration param should be documented.
