### ISSUE TITLE
Improve CLI usability by adding study alias

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#553]
Current CLI ask many times for the _study_, when more than one study exist then _project:study_ must be provided, e.g.

./opencga.sh variant query --gene BRCA2 --count -s _reference_grch37:1kG_phase3_

This is even worse when the study has been shared by a different user, then user@project:study is needed, e.g.:

./bin/opencga.sh variant query --gene BRCA2 --count -s _hgvauser@reference_grch37:1kG_phase3_

This can be annoying and error prone, to improve the usability two different actions are carried out:

1. Add _defaultStudy_ param to _client-configuration.yml_, this will indicate the _study_ to be used (fully qualified name) when _-s, --study_ is not present.
2. Add study _**alias**_ param to _client-configuration.yml_, this will create an alias for each study, this alias will be replaced with the fully qualified name.

An example of the configuration file:

```
# Default study when -s, --study is empty
defaultStudy: "userhgva@reference_grch37:1kG_phase3"

# Alias to different studies, these can be fully qualified: user@project:study
alias:
  1kg_grch37: reference_grch37:1kG_phase3
  exac: reference_grch37:EXAC
  1kg_grch38: reference_grch38:1kG_phase3

```

With this client configuration file the CLI will be:

./bin/opencga.sh variant query --gene BRCA2 --count

or

./bin/opencga.sh variant query --gene BRCA2 --count -s _1kg_grch37_
