### ISSUE TITLE
Improve Solr integration with VariantStorage when querying

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#638]
Currently, variant queries can be executed on the Variant Storage (mongodb or hbase), or on Solr.

We have seen that complex queries using multiple indexes work really good over Solr, and not so good on MongoDB or HBase.

In the query can not be 100% solved by Solr (because it requests or filters by fields not stored in solr) we can decide (using some heuristics) to query first solr to get the ids, and then to the real variant storage.

We expect to see a big speed-up on complex queries (more than 5 filters). 

- [x] Add [embedded Solr](https://wiki.searchtechnologies.com/index.php/Unit_Testing_with_Embedded_Solr) for JUnit tests
- [x] Join Solr results with results from Mongo or Hadoop
  - [x] Implement multi variant iterator
  - [X] Be aware of limit-skip. If base query is not null, will need client side skip
  - Use hbase scan instead of phoenix query for queries fully resolved in solr? Not now.
    Maybe in a future, with `Table#get(List<Get>)` or `MultiRowRangeFilter`
- [x] Implement approximated count
- [x] `summary` parameter should be an alias for a set of included fields

#### New configuration parameters
```yml
intersect.active : true          # Allow intersect queries with the SearchEngine (Solr) 
intersect.always : false         # Force intersect queries 
intersect.params.threshold : 3   # Minimum number of QueryParams in the query to intersect       
```
