### ISSUE TITLE
Add hooks to configuration file

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#856]
In many situations, researchers would like to react and perform additional actions depending on some particular values the data might get. A new section in the catalog configuration file will be added to contain custom hooks where users will be able to decide under which circumstances they might want to set, remove or simply abort the operation being performed.

The new section will look similar to:

``` yaml
 hooks:
    user@project:study:            # Full Qualified Name of the study.
    file:                          # Entity where the hook will be checked (file, sample, cohort...)
     - field: "name"               # Field of the entity to be checked
       value: "~(.*)SV.vcf.gz$"    # Value that needs to be satisfied to perform the hook action
       stage: "CREATE"             # Stage when the hook will be checked (CREATE, UPDATE)
       action: "ADD"               # Action to be performed (ADD, SET, REMOVE, ABORT)
       where: "tags"               # Field over which the action will be performed
       what: "SV"                  # Value to be updated
```
