### ISSUE TITLE
Test OpenCGA with MongoDB Atlas

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#951]
Determine steps required to get OpenCGA working with MongoDB Atlas.

**Comment by martinpeck** [comment]
Linked to #952 (the CosmosDB version of this Issue)

**Comment by martinpeck** [comment]
config required for cluster is similar to:

``` yaml
catalog:
  # offset: Starting point for the catalog internal ids. Use a big offset number (1000000 for instance) if you plan to use numerical ids
  #         for names or aliases of any entity.
  offset: 0
  database:
    hosts:
    - test-shard-00.example.net:27017
    - test-shard-01.example.net:27017
    - test-shard-02.example.net:27017
    user: azure
    password: yourPasswordHere
    options:
      authenticationDatabase: admin
      connectionsPerHost: 20
      sslEnabled: true
      replicaSet: test-shard-0
```
