### ISSUE TITLE
Test OpenCGA with CosmosDB using the MongoDB API

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#952]
Determine steps required to get OpenCGA working with CosmosDB (using MongoDB API).

**Comment by martinpeck** [comment]
Assigning to @bart-jansen so he can take a look at this.

You'll need an SSL-enabled code base, and so you'll need to this PR merged first: 

https://github.com/opencb/java-common-libs/pull/38

**Comment by martinpeck** [comment]
Have switched on 2 preview features, which appears to have allowed me to get further:

https://azure.microsoft.com/en-us/blog/azure-cosmosdb-extends-support-for-mongodb-aggregation-pipeline-unique-indexes-and-more/

- MongoDB aggregation pipeline
- 3.4 wire protocol

I addition, I've configured the catalog DB as follows:

```
catalog:
  # offset: Starting point for the catalog internal ids. Use a big offset number (1000000 for instance) if you plan to use numerical ids
  #         for names or aliases of any entity.
  offset: 0
  database:
    hosts:
    - [Cosmos DB Mongo Server Endpoint Goes Here]
    user: mpeck-ffs
    password: [PASSWORD GOES HERE]
    options:
      authenticationDatabase: admin
      connectionsPerHost: 20
      sslEnabled: true
```
