### ISSUE TITLE
Allow Solr connection to multiple regions and replicas

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#978]
#### Tasks
- [x] Modify the SolrManager to accept multiple hosts.
   If the hosts start with "http" use either HttpSolrClient or LBHttpSolrClient, otherwise use CloudSolrClient
- [x] Modify the configuration files to accept a list of hosts.

Example:
```yml
## Solr Search Configuration
search:
  # List of hosts pointing either to the Solr nodes directly using a complete URL or to the zookeper nodes with HOST:PORT
  #    Example for Solr connection:       http://opencga-solr-01.zone:8983/solr
  #    Example for Zookeeper connection:  opencga-zookeeper-01:2181               <-- Recommended for replicated installations
  hosts:
  - opencga-zookeeper-01:2181
  - opencga-zookeeper-02:2181
  - opencga-zookeeper-03:2181
  mode: "cloud"
  ...
```
